spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-service:8888
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
turbine:
  app-config: shopping-cart-service,inventory-service,order-service,account-service,user-service,catalog-service,online-web-store,edge-service
  cluster-name-expression: new String("default")
  InstanceMonitor:
    eventStream:
      skipLineLogic:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: default
  cloud:
    config:
      uri: http://localhost:8888
spring.profiles.active: development
---
spring:
  profiles: cloud
  cloud:
    config:
      uri: ${vcap.services.config-service.credentials.uri:http://localhost:8888}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.117:8761/eureka/