spring.profiles.active: development
---
spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.100}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:neo4j}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
management:
  endpoint:
    health:
      enabled: true
      show-detail: always
  endpoints:
    jms:
      exposure:
        include: "*"
    web:
      base-path: /actuator
      exposure:
        include: "*"
      cors:
        allowed-origins: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.101}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  client:
    enabled: false